add CPU-X
black-desk/linglong-package-examples pull request #69
Opened 2023-07-05 05:24 UTC by Cdrags

![cpu](https://github.com/black-desk/linglong-package-examples/assets/77877635/87533fe5-bd1d-4540-8f56-1f7123dad426)
run is ok

2023-07-05 05:28 UTC, black-desk requested changes

2023-07-05 05:28 UTC, black-desk commented on io.github.CPU-X/makefile
> +DESKTOP_FILE ?= $(shell cd squashfs-root && ls *.desktop)
从2048里再拿一份makefile 这里对DESKTOP_FILE的处理是不对的.

2023-07-06 05:31 UTC, black-desk commented
squash一下

2023-07-06 05:37 UTC, Cdrags commented
> squash一下

finished

2023-07-06 05:59 UTC, merged