add CRG
black-desk/linglong-package-examples pull request #70
Opened 2023-07-05 05:26 UTC by Cdrags

run is ok
![dd5ffd41f5a083ffd40a906912a1a077](https://github.com/black-desk/linglong-package-examples/assets/77877635/c94e48f5-456b-4610-8581-0f400aef2661)

2023-07-05 05:27 UTC, black-desk requested changes

2023-07-05 05:27 UTC, black-desk commented on io.github.CRG_Data_Tool/makefile
> +DESKTOP_FILE ?= $(shell cd squashfs-root && ls *.desktop)
makefile 从master的2048里再拿一份. 这里对DESKTOP_FILE这个变量的处理是不正确的.

2023-07-06 05:30 UTC, black-desk commented
squash一下

2023-07-06 05:33 UTC, Cdrags commented
> squash一下

finished

2023-07-06 05:59 UTC, merged