add Sup
black-desk/linglong-package-examples pull request #89
Opened 2023-07-05 06:52 UTC by Cdrags

![6fb05893db0617d754b9cf14960b730c](https://github.com/black-desk/linglong-package-examples/assets/77877635/ad81c7ad-13cb-4d3c-91f7-7467d0c11fe8)
run is ok

2023-07-05 06:54 UTC, black-desk requested changes
你的linglong.yaml呢

2023-07-06 02:11 UTC, black-desk commented
squash一下.

2023-07-06 02:31 UTC, Cdrags commented
> squash一下.

done

2023-07-06 02:37 UTC, black-desk commented
> > squash一下.
> 
> done

意思是要把这两个提交合并成一个

![image](https://github.com/black-desk/linglong-package-examples/assets/29726878/bccfa0bb-3d64-4924-91b9-481a67198b3a)

2023-07-06 02:49 UTC, Cdrags commented
> > > squash一下.
> > 
> > 
> > done
> 
> 意思是要把这两个提交合并成一个
> 
> ![image](https://user-images.githubusercontent.com/29726878/251326614-bccfa0bb-3d64-4924-91b9-481a67198b3a.png)

刚刚忘记push了……现在好了

2023-07-06 02:56 UTC, black-desk requested changes

2023-07-06 02:56 UTC, black-desk commented on io.github.Sup/linglong.yaml
> +  id: org.deepin.Sup
名字不要乱取 和文件夹名保持一致.

2023-07-06 02:56 UTC, black-desk commented on io.github.Sup/linglong.yaml
> +  name: deepin-Sup
看看别人怎么写的吧.

2023-07-06 03:39 UTC, black-desk approved these changes

2023-07-06 03:40 UTC, merged